### ISSUE TITLE
Chemfig electron pushing diagrams not rendered correctly

### ISSUE THREAD

**Issue by UnicodeAlt255** [mgieseki/dvisvgm#108]
```latex
\documentclass[varwidth=100cm,border=5pt]{standalone}
\usepackage{mhchem}
\usepackage{chemfig}

\begin{document}

\schemestart
\chemfig{**6(----(-@{O}O-[@{OH_b}:0]@{H}H)--)}
\arrow{->[\chemfig{@{OH_minus}\chemabove{O}{\scriptstyle\ominus}H}]}
\chemleft[
\subscheme{
\chemfig{**6(---@{BT}-[@{BB}](-[@{RO_b}]@{RO}\chemabove{O}{\quad\ominus})--)}
\arrow{<->}
\chemfig{*6(-=-(\chemabove{\lewis{1:,}}{\quad\ominus})-(=O)-=)}
}
\chemright]
\schemestop
\chemmove{
    \draw[shorten <=8pt](OH_minus)..controls +(90:10mm) and +(0:5mm)..(H);
    \draw(OH_b)..controls +(90:5mm) and +(90:5mm)..(O);
    \draw[shorten <=4pt](RO)..controls +(20:3mm) and +(0:5mm)..(RO_b);
    \draw(BB)..controls +(90:5mm) and +(100:5mm)..(BT);
}

\end{document}
```
should look like this:
![pdflatex+imagemagick](https://user-images.githubusercontent.com/12755239/58388230-0927b380-7fd1-11e9-9bc7-bc7d558f5995.png)

but dvisvgm produces this:
![latex+dvisvgm](https://user-images.githubusercontent.com/12755239/58388235-147adf00-7fd1-11e9-8997-cb50c6c88e32.png)

**Comment by mgieseki** [comment]
What version of dvisvgm do you use (`dvisvgm --version`)? The file is converted correctly for me.

**Comment by UnicodeAlt255** [comment]
I'm on 2.3.5. I'm pretty sure you're right, it seems Arch Linux's texlive package has fallen behind.

**Comment by UnicodeAlt255** [comment]
I updated to 2.6.3 and `--pdf` gave me `PostScript error: undefined in GS_PDF_ProcSet`. I'm guessing this has something to do with [Tikz using Postscript features](https://tex.stackexchange.com/questions/5826/tikz-with-positioning-does-not-work-with-dvi). Assuming that's the case, would supporting such things ever be supported in dvisvgm?

**Comment by mgieseki** [comment]
Yes, dvisvgm supports PostScript. It interacts with Ghostscript to process the PS code and to obtain information about the processed operations. Actually, the error message `undefined in GS_PDF_ProcSet`  comes from Ghostscript telling that the internal operator `GS_PDF_ProcSet` can't be found. So, it's a Ghostscript issue. 
Unfortunately, I can't reproduce the problem here. dvisvgm correctly converts the PDF generated from your example. Here's the console output:

```
$ pdflatex chem
[...]
Output written on chem.pdf (1 page, 35650 bytes).
Transcript written on chem.log.

$ dvisvgm --pdf -d2 chem
processing PDF file
  graphic size: 297.05pt x 107.31pt (104.4mm x 37.71mm)
  output written to chem.svg
1 of 1 page converted in 0.373712 seconds
```
What's the Ghostscript version installed on your system? `dvisvgm -V1` lists all libraries linked to the dvisvgm binary, e.g.
```
$ dvisvgm -V1
dvisvgm 2.7.1 (x86_64-pc-linux)
-------------------------------
brotli:      1.0.7
clipper:     6.2.1
fontforge:   20160721
freetype:    2.9.1
Ghostscript: 9.26
kpathsea:    6.3.0
potrace:     1.15
ttfautohint: 1.8.3
xxhash:      0.7.0
zlib:        1.2.11
```

**Comment by mgieseki** [comment]
I just found out that `GS_PDF_ProcSet` [has been removed since Ghostscript 9.27](http://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=4ec9ca74bed49f2a82acb4bf430eae0d8b3b75c9). The current releases of dvisvgm require this operator for PDF conversion and therefore don't work together with GS 9.27.

**Comment by mgieseki** [comment]
I've committed a workaround (bc51951bc90b700c28ea018993bdb058e5271e9b) that should also work with GS 9.27. It will be part of the next dvisvgm release.

**Comment by UnicodeAlt255** [comment]
So I think I figure out how to build and install dvisvgm from the git repo, but I keep getting an error:
```
warning: kpathsea: configuration file texmf.cnf not found in these directories: /usr/local/bin:/usr/local/bin/share/texmf-local/web2c:/usr/local/bin/share/texmf-dist/web2c:/usr/local/bin/share/texmf/web2c:/usr/local/bin/texmf-local/web2c:/usr/local/bin/texmf-dist/web2c:/usr/local/bin/texmf/web2c:/usr/local:/usr/local/share/texmf-local/web2c:/usr/local/share/texmf-dist/web2c:/usr/local/share/texmf/web2c:/usr/local/texmf-local/web2c:/usr/local/texmf-dist/web2c:/usr/local/texmf/web2c://texmf-local/web2c:/usr:/usr/share/texmf-local/web2c:/usr/share/texmf-dist/web2c:/usr/share/texmf/web2c:/usr/texmf-local/web2c:/usr/texmf-dist/web2c:/usr/texmf/web2c.
WARNING: map file ps2pk.map not found
WARNING: map file pdftex.map not found
WARNING: map file dvipdfm.map not found
WARNING: map file psfonts.map not found
WARNING: none of the default map files could be found
pre-processing DVI file (format version 2)
WARNING: PostScript header file tex.pro not found
WARNING: PostScript header file texps.pro not found
WARNING: PostScript header file special.pro not found
WARNING: PostScript header file color.pro not found
PostScript error: undefined in TeXDict
```
So I symlinked:
```
sudo ln -sfv /usr/local/texlive/2019/* /usr/local/bin/share/
sudo ln -sfv /usr/local/texlive/texmf-local/ /usr/local/bin/share/
```

But I still get 
```
WARNING: map file ps2pk.map not found
WARNING: map file pdftex.map not found
WARNING: map file dvipdfm.map not found
WARNING: map file psfonts.map not found
WARNING: none of the default map files could be found
pre-processing DVI file (format version 2)
WARNING: PostScript header file tex.pro not found
WARNING: PostScript header file texps.pro not found
WARNING: PostScript header file special.pro not found
WARNING: PostScript header file color.pro not found
PostScript error: undefined in TeXDict
```

What am I doing wrong here?

**Comment by mgieseki** [comment]
The initial warning message `configuration file texmf.cnf not found` comes from the kpathsea library. It's used to lookup files in the texmf directory tree. If it's not configured correctly or doesn't match the installed TeX system, it can't find the requested files. In this case, it doesn't find the `.map` and `.pro` files required by dvisvgm.
So you probably linked a libkpathsea that doesn't work correctly with your TeX installation. Please also see #62, #78, #80, and #96 for related questions. Unfortunately, I can't really help here because it's not an issue with dvisvgm.

**Comment by UnicodeAlt255** [comment]
Thank you so much for your assistance. I managed to make the built dvisvgm work in Arch Linux by following [this advice](https://github.com/mgieseki/dvisvgm/issues/62#issuecomment-375903211), and running `pdflatex` twice then `dvisvgm --pdf` produced the correct output. Running `latex` twice and running `dvisvgm` however still did not produce the correct output.

Should it be expected that `dvisvgm --pdf` must be used in this case? Or did you manage to get it working with `latex` and just `dvisvgm`?

**Comment by mgieseki** [comment]
> Thank you so much for your assistance. I managed to make the built dvisvgm work in Arch Linux by following [this advice](https://github.com/mgieseki/dvisvgm/issues/62#issuecomment-375903211), and running `pdflatex` twice then `dvisvgm --pdf` produced the correct output. 

Great, I'm glad to hear you got everything working out now.

>Running `latex` twice and running `dvisvgm` however still did not produce the correct output. 
> Should it be expected that `dvisvgm --pdf` must be used in this case? Or did you manage to get it working with `latex` and just `dvisvgm`?

To me, It seems there is a bug in `chemfig`, `mhchem` or even `tikz` because dvips and dvisvgm produce the same wrong results. So I guess the conversion from DVI to SVG works correctly but the DVI file contains incorrect PostScript data created by one of the packages. Maybe you can ask the package maintainers if there's anything they can do.

**Comment by UnicodeAlt255** [comment]
I'll wait a couple years, if I still have issues I'll try asking the package maintainers.
