### ISSUE TITLE
xdv conversion failed with TikZ graphics

### ISSUE THREAD

**Issue by roland65** [mgieseki/dvisvgm#109]
Hi Martin,

this is Roland Baudin, developer of the TexMaths extension for LibreOffice.

A TexMaths user sent me an example of TikZ graphics that dvisvgm converts well from dvi (obtained from latex) but not from xdv (obtained from xelatex). In that case the output svg is empty.

You'll find in the attached archive two .tex files. First file 'test_latex.tex' can be compiled with latex and the output dvi is well converted with dvisvgm like this:

latex test_latex.tex
dvisvgm -n1 -e test_latex.dvi

SVG file test_latex.svg is correct and shows some polyhedra.

Second file 'test_xelatex.tex' only differs in the preamble (commands \usepackage{fontspec} and \usepackage{unicode-math} are added) to allow its compilation with xelatex:

xelatex -no-pdf test_xelatex.tex
dvisvgm -n1 -e test_xelatex.xdv

In that case, the output SVG file test_xelatex.svg is empty.

If I compile 'test_xelatex.tex' to obtain a pdf output instead of xdv:

xelatex test_xelatex.tex

then the pdf output is correct and shows the polyhedra.

My system: Ubuntu Linux 18.04.2 64 bits
latex version: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
xelatex version: XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)
dvisvgm version: 2.1.3 (TeX Live 2017/Debian)

I also tried with your latest dvisvgm 2.7.1 (self compiled) and got the same issue.
[test.zip](https://github.com/mgieseki/dvisvgm/files/3226743/test.zip)

**Comment by mgieseki** [comment]
Hi Roland,

the problem here is that with the current settings XeLaTeX creates PDF `\special` statements which dvisvgm doesn't support. If you add `dvips` to the document class options, the specials are replaced with PostScript ones. So, changing the first line to
```tex
\documentclass[10pt,dvips]{article}
```
leads to a XDV file that dvisvgm can process correctly.

**Comment by roland65** [comment]
Thanks Martin! That's what I call an easy fix...
Do you think I can safely replace \documentclass[10pt]{article} with \documentclass[10pt,dvips]{article} every time or are there some issues related to the dvips directive?

**Comment by mgieseki** [comment]
As far as I can tell, `latex` uses the dvips driver by default when generating DVI files. So I guess that adding it to the template for `xelatex` shouldn't hurt as long as it's used in conjunction with command-line option `-no-pdf`. But I'm not a XeTeX expert. Since XeTeX primarily targets PDF output, there might be some cases where the dvips driver doesn't work as expected and dvisvgm can't properly convert the resulting XDV file. However, I have never personally encountered such an example so far.

**Comment by roland65** [comment]
OK, thanks for the explanation. I'll change my TexMaths workflow accordingly for XeLaTeX.
Of course, you can close this ticket.
And thanks again for the fast and useful answer!

**Comment by mgieseki** [comment]
I'm glad I could help. Let me know if you find any further issues.
