### ISSUE TITLE
Bounding box behaviour

### ISSUE THREAD

**Issue by JohannesNaegele** [mgieseki/dvisvgm#126]
Hey, I don't understand how to correctly specify the corners in --bbox. Shouldn't 

- `dvisvgm --font-format=woff --exact --zoom=-1 --bbox=0mm,0mm,210mm,297mm`
- `dvisvgm --font-format=woff --exact --zoom=-1 --bbox=A4`

produce the same output?

At least they don't on the uploaded `.dvi`...
[test.zip](https://github.com/mgieseki/dvisvgm/files/4056247/test.zip)

**Comment by mgieseki** [comment]
According to the DVI specification, origin (0, 0) is not located directly in the top left corner of a sheet of paper but 1 inch away from the top and left edge. So, if you specify a paper format like `A4`, dvisvgm arranges the page contents accordingly, i.e. the actual bounding box of `A4` is `-1in,-1in,210mm-1in,297mm-1in`. That's why you get different results.
