### ISSUE TITLE
It keeps getting built with Ghostscript 9.26

### ISSUE THREAD

**Issue by iamtekeste** [mgieseki/dvisvgm#137]
First, I want to say thank you for creating this tool!

From reading other issues I know that I need to use Ghostscript 9.52 and not Ghostscript 9.26. I have built GS from the source and running `gs` reports that I have the latest version. Here is part of the output.
```
GPL Ghostscript 9.52 (2020-03-19)
Copyright (C) 2020 Artifex Software, Inc.  All rights reserved.
```
After compiling & installing GS from source I did the same for `dvisvgm` too, but when I run `dvisvgm -V1` it is telling me the GS version is 9.26.
```
dvisvgm 2.9.1 (x86_64-pc-linux-gnu)
-----------------------------------
brotli:      1.0.7
clipper:     6.2.1
fontforge:   20160721
freetype:    2.6.3
Ghostscript: 9.26
kpathsea:    6.2.2
potrace:     1.16
xxhash:      0.7.3
zlib:        1.2.8
```
What or how should I compile dvisvgm to make it pick up the 9.52 version?

Here is what my Dockefile looks like
```sh
FROM node:12

RUN apt-get update && apt-get install -y build-essential texlive texlive-lang-english libkpathsea-dev

RUN wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs952/ghostscript-9.52.tar.gz -O /tmp/ghostscript.tar.gz \
    && tar -xzf /tmp/ghostscript.tar.gz -C /tmp \
    && cd /tmp/ghostscript-9.52 \
    && ./configure --prefix=/usr \
        --disable-compile-inits \
        --enable-dynamic        \
        --with-system-libtiff \
    && make \
    && make so \
    && make install \
    && make soinstall \
    && install -v -m644 base/*.h /usr/include/ghostscript \
    && ln -sfvn ghostscript /usr/include/ps


RUN wget https://github.com/mgieseki/dvisvgm/archive/2.9.1.tar.gz -O /tmp/dvisvgm.tar.gz \
    && tar -xzf /tmp/dvisvgm.tar.gz -C /tmp \
    && cd /tmp/dvisvgm-2.9.1 \
    && ./autogen.sh \
    && ./configure --enable-bundled-libs \
    && make \
    && make install
```

**Comment by mgieseki** [comment]
I guess, there's still an old Ghostscript library installed on your machine which is used by the (dynamic) linker. Maybe you need to call `ldconfig` after installing the new GS libs.

In order to tell what's happening, I need some more information:
* Could you provide the output of `./configure --enable-bundled-libs`?
* What's the output of `/path/to/dvisvgm | grep libgs`?
* What's the output of `ldd /path/to/dvisvgm | grep libgs`?

**Comment by iamtekeste** [comment]
Thank you for the quick reply!
So it turns out you are right, it looks like just running the first command `apt-get update && apt-get install -y build-essential texlive texlive-lang-english libkpathsea-dev` is installing GS 9.26.
I guess, the question now is how do I point it to use the one I installed from the source?

Running `/usr/local/bin/dvisvgm | grep libgs` does not return anything.

Output for `ldd /usr/local/bin/dvisvgm | grep libgs`
```
	libgs.so.9 => /usr/lib/x86_64-linux-gnu/libgs.so.9 (0x00007fa437024000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fa433a30000)
```

Output for `./configure --enable-bundled-libs` from `config.log`
https://gist.github.com/iamtekeste/68adee59c68685613b513fd5c72ecc53


Output of `ldconfig -v | grep libgs`
```
ldconfig: Path `/lib/x86_64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/x86_64-linux-gnu' given more than once
ldconfig: /lib/x86_64-linux-gnu/ld-2.24.so is the dynamic linker, ignoring

	libgssapi_krb5.so.2 -> libgssapi_krb5.so.2.2
	libgssrpc.so.4 -> libgssrpc.so.4.2
	libgs.so.9 -> libgs.so.9.26
	libgs.so.9 -> libgs.so.9.52
```

**Comment by mgieseki** [comment]
Ok, thanks for the additional information. According to the config log, the linker finds `libgs.so` which points to `libgs.so.9` and links it to the binary. So that's fine.
Now you should check where symlink `/lib/x86_64-linux-gnu/libgs.so.9` points to: `libgs.so.9.26` or `libgs.so.9.52`? It's probably the former one because the dynamic linker loads the older library when you call dvisvgm. If that's the case, it should be sufficient to update the symlink.

**Comment by iamtekeste** [comment]
I am noob linux user, but after googling I used `readlink -f /lib/x86_64-linux-gnu/libgs.so.9` to find out where it points too, and the output I got is `/lib/x86_64-linux-gnu/libgs.so.9`.
Does that sound right?

**Comment by mgieseki** [comment]
It seems, your `libgs.so.9` isn't a symlink but a regular file which doesn't sound right.
What's the output of `ls -l /lib/x86_64-linux-gnu/libgs.so*`? It should look something like this:
```
lrwxrwxrwx. 1 root root       13  6. Apr 12:56 /usr/x86_64-linux-gnu/libgs.so -> libgs.so.9.52
lrwxrwxrwx. 1 root root       13  6. Apr 12:56 /usr/x86_64-linux-gnu/libgs.so.9 -> libgs.so.9.52
-rwxr-xr-x. 1 root root 16610040  6. Apr 12:56 /usr/x86_64-linux-gnu/libgs.so.9.52
```
`libgs.so` and `libgs.so.9` are symbolic links that both reference `/usr/lib64/libgs.so.9.52` here.

**Comment by iamtekeste** [comment]
That is weird, mine says `ls: cannot access '/lib/x86_64-linux-gnu/libgs.so*': No such file or directory`

I feel bad for taking too much of your time so I will try to figure out how I can make the latest library the default one like you suggested.

Building `dvisvgm` from source on linux is really difficult huh? I am thinking if I figure it out I might send a PR with instructions. :)

**Comment by mgieseki** [comment]
That's no problem. It doesn't take much time to type in some suggestions. So no need to feel bad. :)

It seems that building dvisvgm isn't the problem here since you get a running binary. But Ghostscript isn't updated properly. What Linux distro do you use? Isn't there a more recent GS package you can simply update using the package manager without having to build it yourself?

Anyway, I forgot a leading `usr` in the path. Please try again with `la -l /usr/lib/x86_64-linux-gnu/libgs.so*`.

**Comment by iamtekeste** [comment]
Now I got something,
```
lrwxrwxrwx 1 root root       13 Nov 13  2019 /usr/lib/x86_64-linux-gnu/libgs.so.9 -> libgs.so.9.26
-rw-r--r-- 1 root root 16291752 Nov 13  2019 /usr/lib/x86_64-linux-gnu/libgs.so.9
```

You are right it is pointing to the 9.26 version. How do I got about updating it? And would I need to rebuild `dvisvgm` again?

Unfortunately the latest from the package manager is 9.26.

**Comment by mgieseki** [comment]
Ok, better than nothing. At least it explains why dvisvgm use the older GS version. The newer files are probably in `/usr/lib` or `usr/lib64`? Could you check again with `ls -l /usr/lib/libgs.so*`?
Since both `libgs.so.9.26` and `libgs.so.9.52` have the same soname (which is libgs.so.9), you don't need to rebuild dvisvgm. You just have to ensure it can find the newer library, e.g. by moving the corresponding files to `/usr/lib/x86_64-linux-gnu/`.

**Comment by iamtekeste** [comment]
Output of `ls -l /usr/lib/libgs.so*`
```
lrwxrwxrwx 1 root root       13 Jun 23 02:04 /usr/lib/libgs.so -> libgs.so.9.52
lrwxrwxrwx 1 root root       13 Jun 23 02:04 /usr/lib/libgs.so.9 -> libgs.so.9.52
-rwxr-xr-x 1 root root 15964088 Jun 23 02:04 /usr/lib/libgs.so.9.52
```
So should I move these files to `/usr/lib/x86_64-linux-gnu/` ?

**Comment by mgieseki** [comment]
You can copy the files with `cp -a /usr/lib/libgs.so* /usr/lib/x86_64-linux-gnu/`. The `-a` switch ensures that symlinks stay symlinks in the target folder. Existing files are overwritten.

**Comment by iamtekeste** [comment]
Sweet! That did it. Thank you so much! Closing the issue now.

**Comment by mgieseki** [comment]
Great, I'm glad to hear that you could finally get everything running.
