### ISSUE TITLE
Certain parts removed from circuitikz image

### ISSUE THREAD

**Issue by matthuszagh** [mgieseki/dvisvgm#139]
I draw circuit schematics with [circuitikz](https://github.com/circuitikz/circuitikz). I've recently noticed that some of the output is being removed when dvisvgm converts the pdf to an svg file. For example, here is a minimal input tex file:

mwe.tex:
```tex
\documentclass[border={0pt 1pt}]{standalone}
\usepackage[american]{circuitikz}

\begin{document}
\begin{circuitikz}
\draw (0,0) to[R,o-] ++(0,2) node[vcc]{};
\end{circuitikz}
\end{document}
```

When I compile this with pdflatex:
```
$ pdflatex mwe.tex
```
I get the expected output:

![dvisvgm_pdf_issue](https://user-images.githubusercontent.com/7377393/88208796-99c64780-cc06-11ea-999c-e87553aaf477.png)

However, when I subsequently convert this to an svg with
```
dvisvgm --pdf mwe.pdf -n -b min -c 10 -o mwe.svg
```

the circle at the bottom is dropped:

![dvisvgm_svg_issue](https://user-images.githubusercontent.com/7377393/88209170-26710580-cc07-11ea-80cb-3f9620d6d50b.png)

This is not a cropping issue, since the circle can be in the middle of the image and still be dropped.

I've tried to make this example as minimal as possible. However, I understand circuitikz/tikz are doing a lot under the hood, so please let me know if I can clarify anything.

I'm using dvisvgm 2.9.1 and circuitkz 1.2.2.

---

Here's another example:
```tex
\documentclass[border={0pt 2pt}]{standalone}
\usepackage[american]{circuitikz}

\begin{document}
\begin{circuitikz}
\def\block{node[dipchip, fill=red]}
\draw (0,0) \block{red};
\end{circuitikz}
\end{document}
```

pdf:
![dvisvgm_pdf_issue](https://user-images.githubusercontent.com/7377393/88210449-165a2580-cc09-11ea-9fcb-c8e7c9bccd7d.png)

svg:
![dvisvgm_svg_issue](https://user-images.githubusercontent.com/7377393/88210466-1bb77000-cc09-11ea-9393-eaac3084e104.png)

Does dvisvgm omit certain layers from the output? My initial guess is that circuitkz is drawing the missing elements on another layer.

**Comment by mgieseki** [comment]
The missing graphics objects are a result of internal changes introduced in Ghostscript 9.52. Some PDF drawing operators are no longer accessible by external applications like dvisvgm and therefore can't be redefined. Unfortunately, there isn't much I can do about it. If you replace GS 9.52 (or later) with GS 9.50, dvisvgm should produce correct results. You could also use `latex` rather than `pdflatex` and convert the DVI file.

**Comment by matthuszagh** [comment]
Thanks for the prompt reply.

That's unfortunate about Ghostscript. Is the intention to continue to provide PDF conversion with limited support, or is there some hope of a workaround eventually?

If anyone else comes across this and wants an alternative to the two options listed above (I had trouble reverting to GS 9.50 and experienced bugs unrelated to dvisvgm when using standalone with luatex to produce a DVI file), I found that inkscape seems to do a good job of converting PDF to SVG. I haven't tested this thoroughly, but I've had good luck so far with

```
inkscape --pdf-poppler in.pdf -T -l -o out.svg
```

`--pdf-poppler` and `-T` convert the fonts to paths.

**Comment by mgieseki** [comment]
> That's unfortunate about Ghostscript. Is the intention to continue to provide PDF conversion with limited support, or is there some hope of a workaround eventually?

I'll have a look if there's a way to work around this specific issue but can't promise yet that it's technically possible. I plan to keep the limited PDF support as long as possible. Unfortunately, each of the recent Ghostscript releases introduced further restrictions because of security reasons. If at some point future restrictions limit the functionality of dvisvgm too much, I'll possibly have to drop PDF support.

You might want to have a look at `mutool` which is part of [mupdf](https://mupdf.com). It's also able to convert PDF to SVG.

**Comment by matthuszagh** [comment]
Thanks for the pointer, I'll take a look at `mutool` as well.

**Comment by mgieseki** [comment]
I've added a patch that should work around the issue. At least, it leads to correct results for the two examples above when using dvisvgm with GS 9.52.
