### ISSUE TITLE
Is it possible to retrieve depth value from SVG viewBox?

### ISSUE THREAD

**Issue by matthuszagh** [mgieseki/dvisvgm#160]
I'm attempting to align the baseline of SVG images to the baseline of surrounding text. From the documentation and discussion in this repo, it seems that using depth is the correct way to go about this. It appears that the depth parameter is equal to the sum of height and min-y components of `viewBox`. Is this correct and always true?

For example, if I compile the following latex file:

```tex
\documentclass[preview]{standalone}
\usepackage{amsmath}
\usepackage{amsfonts}
\begin{document}
$x\times y\cdot z$
\end{document}
```

with

```
$ latex file.tex
$ dvisvgm -e -n file.dvi
```

I see the output

```
pre-processing DVI file (format version 2)
processing page 1
  computing extents based on data set by preview package (version 12.2)
  width=35.091148pt, height=4.91pt, depth=2.05pt
  graphic size: 35.091148pt x 6.96pt (12.333128mm x 2.44616mm)
  output written to scratch.svg
1 of 1 page converted in 0.208363 seconds
```

The generated SVG file contains:

```xml
<svg ... width='34.960048pt' height='6.933998pt' viewBox='0 -4.891656 34.960048 6.933998'>
```

2.05 ~= (6.933998-4.891656)*72/72.27

Is this a coincidence for this particular example, or always true?

I'm using dvisvgm 2.11.1.

**Comment by mgieseki** [comment]
> 2.05 ~= (6.933998-4.891656)*72/72.27

This is not quite correct because the values of the `viewBox` attribute are given in PostScript points ("big points", bp), and dvisvgm outputs TeX point (pt) values to the console. Thus, you get

    2.05pt ~= (6.933998bp - 4.891656bp) * (72.27pt/in) / (72bp/in)

So, if you want to use the depth values to adapt the baselines, you probably need to convert it back to PostScript points.  

> Is this a coincidence for this particular example, or always true?

Unfortunately, these values are not always reliable because DVI files don't differentiate between height and depth of a box. However, in most cases, the preview package places the first baseline at 0 so that the positions of the top and bottom borders of the bounding box enclosing the text can be evaluated to derive height and depth.
Alternatively, you can use option `--bbox=preview`. It tells dvisvgm to directly apply the values embedded by the preview package without further assumptions and computations.
