### ISSUE TITLE
Fedora copr package conflicts with distro package

### ISSUE THREAD

**Issue by awehrfritz** [mgieseki/dvisvgm#181]
The `dvisvgm` package from the copr repository conflicts with the `texlive-dvisvgm` package from the official repositories.

This should be explicitly stated in the rpm spec file such that the package manager can take care of this properly:
``` spec
Conflicts: texlive-dvisvgm
```

I could not find the spec file in the repository, hence just this bug report here.

For further reference, see also:
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_conflicts
https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages

**Comment by mgieseki** [comment]
Thanks for the hint. The dvisvgm package from Copr is supposed to provide an update for `texlive-dvisvgm` and should obsolete the latter instead of conflicting with it. I just had to update the epoch of `texlive-dvisvgm` referenced in the spec file which was outdated. The new package currently being built should fix the issue.

The sources for the Copr builds of dvisvgm are located in its own Git repository. The link can be found [here](https://copr.fedorainfracloud.org/coprs/mgieseki/dvisvgm/package/dvisvgm).
