### ISSUE TITLE
[general question] Which verison am I using?

### ISSUE THREAD

**Issue by VincentTam** [mgieseki/dvisvgm#184]
The console's output doesn't seem to match the version info on the GUI.

```
C:\Users\xxxx>dvisvgm -V1
dvisvgm 2.11.1
--------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.3
Ghostscript: 9.25
kpathsea:    MiKTeX 22.3
potrace:     2.11.1
xxhash:      0.8.1
zlib:        1.2.11

C:\Users\xxxx>which dvisvgm
/c/Users/xxxx/AppData/Local/Programs/MiKTeX/miktex/bin/x64/dvisvgm

C:\Users\xxxx>
```

The sys info dialog says "version: 2.13.3".

![miktex-dvisvmg-bin-x64](https://user-images.githubusercontent.com/5748535/172232546-727a6aea-1fa4-4122-afaf-983fa2470396.png)

**Comment by mgieseki** [comment]
According to the dvisvgm output, you're using version 2.11.1. But maybe the MiKTeX maintainers change or adapt the sources somehow so that the wrong version is shown. This is a MiKTeX-specific problem, so that I can't help here. You should report the differing version numbers in the [MiKTeX issue tracker](https://github.com/MiKTeX/miktex/issues).

**Comment by VincentTam** [comment]
thx for reply
