### ISSUE TITLE
feature request: Docker environment

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [mgieseki/dvisvgm#188]
Hi, thanks for that useful package!

Is it planned to release a Docker image?

I am happy to help if need be.

**Comment by mgieseki** [comment]
Thanks for your feedback. I currently don't plan to provide a Docker image because I'm not sure if it's really necessary. dvisvgm has a lot of dependencies and especially requires a TeX environment. There are already Docker images available for many TeX distributions, including TeX Live and MiKTeX. They also provide dvisvgm because it has been added to these distributions in the past. Or do you have a different scenario in mind?

**Comment by RemDelaporteMathurin** [comment]
Ah yes I guess if the package is in the texlive docker image it should be enough! Thanks for replying!
