### ISSUE TITLE
DVISVGM don't come back to the command prompt.

### ISSUE THREAD

**Issue by vipa7070** [mgieseki/dvisvgm#191]
In the past version, this was the behavior:
![correct](https://user-images.githubusercontent.com/46306351/179399488-c448beca-5a3a-429c-9905-7ff5bc54442e.png)
Starting from the last versions (from 2.12 on, I think) on my system, DVISVGM don't come back to the command prompt:
![probl](https://user-images.githubusercontent.com/46306351/179399605-46e56620-06ee-4827-863e-2530f7ceac88.png)
I use the precompiled build from https://dvisvgm.de/Downloads/. Can it be a build problem?

**Comment by mgieseki** [comment]
I currently can't reproduce the issue because I don't have a Windows 7 system available. According to [this webpage](https://miktex.org/kb/prerequisites-2-9), the recent MiKTeX releases require at least Windows 10, so Windows 7 doesn't seem to be officially supported any longer which might lead to unexpected behavior. This probably also affects the COM bindings used by my dvisvgm builds.
If the dvisvgm binaries that come with MiKTeX still work, I suggest to use these instead because they don't rely on the COM interface.
