### ISSUE TITLE
Feature Request: specify output directory

### ISSUE THREAD

**Issue by erwindenboer** [mgieseki/dvisvgm#193]
Hello, 
Is it possible to add an option to specify the output directory of the svg file? This will help me organize all the svg files.
Thanks in advance!

**Comment by mgieseki** [comment]
You can specify the output directory as part of the [output pattern](https://dvisvgm.de/Manpage/#opt-output). e.g. `--output=myfolder/%f` or `-o ../../myfolder%f-%p`. The folders must exist in advance, though, because dvisvgm doesn't create missing directories.
So a separate option isn't really needed. Or are you missing anything special here?
