### ISSUE TITLE
Running test suite with version 3.0 and gs10?

### ISSUE THREAD

**Issue by hpreusse** [mgieseki/dvisvgm#204]
This is rather a question than a report. I've packaged version 3.0 for Debian and uploaded it into the experimental distribution.

Recently the maintainer of the ghostscript package decided to upload version 10, which made v3 build fail (see commit 9bf81fd0b6e7876e5079e917ed7e12163b9e7f7f, which was not applied to v3.0 branch). We removed the build depend on libgs and could fix the build failure. Unfortunately I did not manage to get the test suite running until now. I added a few packages as Depend of the test suite (mupdf-tools, libgs-dev, ghostscript), nevertheless the tests GhostscriptTest & PSInterpreterTest fails. The [log is attached](https://github.com/mgieseki/dvisvgm/files/9956212/test-suite.log), maybe you could give us a hint how to solve the issue. Many thanks!

**Comment by mgieseki** [comment]
Thanks for the info. The GS-related tests should actually be improved in order to prevent failures if libgs can't be loaded. For now, I'd suggest to either exclude the failing tests from your builds or to apply commit 9bf81fd0b6e7876e5079e917ed7e12163b9e7f7f locally in order to allow for linking GS 10. After a bit more testing, I'll merge the v3.0 branch into master in the next couple of weeks.

**Comment by hpreusse** [comment]
OK, thanks. Works for now. Feel free to close the ticket.
