### ISSUE TITLE
Feature Request: option to remove background as Option

### ISSUE THREAD

**Issue by povpie** [mgieseki/dvisvgm#217]
It would be great if there was also an option to remove the background completely. (pdf to svg with mutools in my case).

(using -Oall) Pdf gets converted with a few boxes inside `<defs></defs>` and a few boxes inside <page 1> as background. I use my svgs as overlays so I have to manually remove all background before using them, if dvisvgm could do that automatically it would be awesome.

Example: 
![clut](https://user-images.githubusercontent.com/91896759/212391443-382321a3-8b8a-4b86-991d-07db0c02aa93.png)

Final result after deleting:
![image](https://user-images.githubusercontent.com/91896759/212391858-4739b3a8-d60a-448b-bf77-2efb2baa0ec1.png)

**Comment by mgieseki** [comment]
Unfortunately, that's not an easy task. The question is: Which graphics object is considered the background? There is usually no information available to identify background components. The objects are drawn sequentially, one after the other, so that "later" objects may be rendered on top of the ones already drawn (painters model). The first object could be a background rectangle if it encloses all following ones but that's not certain.
Instead of removing the background in the SVG, it's probably easier to prevent creating one in the PDF.

**Comment by povpie** [comment]
I have tried with multiple softwares to delete the background but your comment made me realize that the backgrounds are just other elements. So I was able to delete all of them in acrobat Pro. There's still one box that stays but it's much simpler now. Thanks Martin. Solved.

**Comment by mgieseki** [comment]
Ok, glad to hear you found a solution that works for you. I'm closing here for now.
