### ISSUE TITLE
Problem with Text-Rendering

### ISSUE THREAD

**Issue by klartext** [mgieseki/dvisvgm#278]
This little snippet from a checklist is rendered not correctly:

```
Lampe\\
Ohrenstöpsel\\
Zahnbürste\\
```

Results (from dvipdf and dvisvgm):

![soll](https://github.com/user-attachments/assets/5adc02b6-6817-4392-985c-8a927d39eecf)
![sein](https://github.com/user-attachments/assets/71acd02b-31f6-49e6-b58f-afd933cc5059)

**Comment by klartext** [comment]
Complete example:

```
\documentclass[12pt,twoside,DIV=12, twocolumn]{scrbook}
\usepackage[utf8]{inputenc}
\setlength{\parindent}{0em}

\begin{document}
Lampe\\
Ohrenstöpsel\\
Zahnbürste\\
\end{document}
```

**Comment by mgieseki** [comment]
I can't reproduce this at the moment. What's your version of dvisvgm? Please also add the command-line statement used to call dvisvgm.
It's probably not an issue with dvisvgm but with the SVG renderer. I suggest to call dvisvgm with option `--no-fonts` or `--font-format=woff2`. Also see the the corresponding info in the [FAQ](https://dvisvgm.de/FAQ).

**Comment by klartext** [comment]
Version: dvisvgm 3.4.2

With `--no-fonts` the output looks fine.

**Comment by mgieseki** [comment]
Ok, then it's actually an issue with the SVG viewer/renderer that can't handle embedded (SVG) fonts.

**Comment by klartext** [comment]
So, you mean `sxiv` and `firefox` both do the rendering wrong, and both wrong in the same way, but `dvisvgm` creates the correct output?

**Comment by mgieseki** [comment]
Yes. Both sxiv and Firefox don't support SVG fonts as created by default (see [here](https://caniuse.com/svg-fonts) for example). If you replace them with TTF, WOFF or WOFF2 fonts (using option [`--font-format`](https://dvisvgm.de/Manpage#opt-font-format)), the SVG files should be rendered correctly.
Alternatively, option [`--no-fonts`](https://dvisvgm.de/Manpage#opt-no-fonts) replaces all glyphs by paths so that no fonts are used at all. But then text can't be searched or selected either.
[Apache Squiggle](https://xmlgraphics.apache.org/batik/tools/browser.html) supports SVG fonts but none of the other formats. If you like, you could check your files with it too.

**Comment by klartext** [comment]
`--font-format=woff2` does help for firefox, but not for sxiv.
`--no-fonts` works for both.

**Comment by klartext** [comment]
From the overview page to the browser-support-table you referenced:
> Method of using fonts defined as SVG shapes. Removed from SVG 2.0 and considered as a deprecated feature with support being removed from browsers.

Deprecated feature...
... I guess I will use `--no-fonts` by default then.
The FAQ reads a bit like (my impression)  "in the future, when browsers become better, they may support the fonts", but when it is deprecated, I don't think expecting this would make sense.

Regarding the searchability: isn't it possible to embed invisible text below the path that creates the text shape?
