### ISSUE TITLE
Texts in converted svg files not selectable

### ISSUE THREAD

**Issue by xuhdev** [mgieseki/dvisvgm#50]
`test.tex`: the following LaTeX source code:

```latex
\documentclass{article}

\pagestyle{empty}

\begin{document}
Hi this is some texts.
\end{document}
```

Generate the dvi file:

    latex test.tex

Convert it to svg:

    dvisvgm -n test.tex

Open the file in a web browser, I found the texts are not selectable. However, if I converted it with inkscape (`dvi-->pdf-->svg` path), the texts are selectable.

**Comment by mgieseki** [comment]
If you call dvisvgm without option `-n`, you get an SVG file with font and text elements rather than graphics paths. The text of these files is usually selectable in the browser or SVG viewer. However, most web browsers don't support font elements so that the result looks wrong.

I don't quite understand how you convert the files to SVG using Inkscape. Do you call `pdflatex` and then use Inkscape's function `File` > `Import`? What additional options do you select in the import dialog?

**Comment by xuhdev** [comment]
@mgieseki  I made the conversion using the following steps:

```
pdflatex test.tex
inkscape -z test.pdf --export-plain-svg=test.svg
```

I can understand your point, but I still don't know why inkscape works...

**Comment by xuhdev** [comment]
I see that inkscape does not convert some complicated texts well, which should be the same as `dvisvgm` without `-n` option. Thanks for your reply.

**Comment by mgieseki** [comment]
Thanks for the additional info.
Inkscape doesn't embed the glyph data into the SVG file but reference external font files. So the browser loads the font file and takes the glyphs from there. Unfortunately, this doesn't work in all cases. There are TeX fonts containing glyphs that are not reachable by Unicode, e.g. big integral or sum signs (also see [this question on TeX.SX](http://tex.stackexchange.com/questions/282340/how-to-create-non-outlined-svg-files-from-latex-formulae/282594)). I'm already looking for a way to find a solution for this problem.
