### ISSUE TITLE
Ghostscript didn't work on windows x64 properly 

### ISSUE THREAD

**Issue by MohamedSayedAly** [mgieseki/dvisvgm#53]
Hi,
I have a small problem here with dvisvgm on windows 8.1 x64 version, that all SVGs lack of spaces produced by ghostscript which made some characters stick to the SVG after and before.
I Use _--libgs_ option to give the path of ghostscript library to dvisvgm.
_NOTE:_ This issue didn't appear on windows 7 x32 version with the same dvisvgm 9.15 but x32 version and ghost script 9.18 x32.

**Comment by mgieseki** [comment]
In order to find the reason for your problem, I need some more information:
- Does dvisvgm print a warning message during the conversion?
- Do you use the 64bit version of the Ghostscript DLL (gsdll64.dll)?
- Please provide a short example demonstrating the problem (attach a ZIP containing the TeX, DVI, and SVG files).
- Post the call of dvisvgm including all command-line options.

**Comment by MYOGEO** [comment]
Hi Martin,
Please forgive me for my late response but I was in vacation for 4 days because i was sick.
Regarding this issue:

1. dvisvgm didn't print any warning messages during conversion.
2. Yes, I use the the 64bit version of the Ghostscript DLL (gsdll64.dll).
3. Attached is a _**DVISVGM_Sample.zip**_ which contains .svg created by dvisvgm, .dvi file which the svg created from, and text file contains the full command line used to run dvisvgm.
[DVISVGM_Sample.zip](https://github.com/mgieseki/dvisvgm/files/161394/DVISVGM_Sample.zip)

**Comment by mgieseki** [comment]
Hi Mohamed,

thanks for providing the additional information and I hope, you're doing well again.

Unfortunately, I'm unable to reproduce your issue without the TeX file because it might contain relevant data. If doable, please try to reduce the TeX file as much as possible, i.e. remove everything not really required, so that it just contains enough information to demonstrate the problem and that you are allowed to share it. You can also send it to me privately if you prefer that.

Best regards,
Martin

**Comment by MYOGEO** [comment]
HI Martin,
Please check your email, I sent you a zip file contains the .TeX file used according to your request.
_NOTE_ I use the following email to send the data, martin.gieseking@uos.de, so if this email is wrong please let me know.
Thanks,
Mohamed

**Comment by mgieseki** [comment]
Hi Mohamed,

I received your email and already replied to it a couple of days ago. Here's an excerpt of it:
Unfortunately, the example is way too complex. I had to install and configure a whole bunch of additional packages as well as the commercial Minion fonts which I don't own. Please try to reduce it significantly by dropping everything that is not actually required to reproduce your problem. If that's not possible, I have to invest a lot of time which I can't offer for free.

Regards,
Martin

**Comment by MYOGEO** [comment]
Hello Martin,
Attached is the same example but with minimum requirements and I think that
this example will be helpful because I am using the normal class (article)
and only important packages *geometry* and *preview, *I am also using font
size to simulate exactly our needs.

Best Regards,

Mohamed

**Comment by mgieseki** [comment]
We've discussed this privately. For the record, here's the hint that solved the issue:
As of [version 1.14](http://dvisvgm.bplaced.net/News#f2ea1bb15d0cd6060ef147407b08dd11), it's necessary to call dvisvgm with option `--bbox=preview` in order to apply the bounding box set by the preview package. Without this option dvisvgm computes a tight bounding box and accordingly adjusts the width, height, and depth values printed during the conversion. Also see the [corresponding info in manual page](http://dvisvgm.bplaced.net/Manpage#specials-ps).

Example:
<pre>
$ dvisvgm test
pre-processing DVI file (format 2)
processing page 1
  <b>computing extents based on data set by preview package (version 11.89)
  width=97.9209pt, height=13.5282pt, depth=8.61124pt</b>
  page size: 97.9209pt x 22.1394pt (34.4153mm x 7.78112mm)
  page written to test.svg
1 of 1 page converted in 0.176034 seconds
</pre>
<pre>
$ dvisvgm <b>--bbox=preview</b> test
pre-processing DVI file (format 2)
processing page 1
  <b>applying bounding box set by preview package (version 11.89)
  width=99.1669pt, height=14.1131pt, depth=9.11311pt</b>
  page size: 99.1669pt x 23.2262pt (34.8532mm x 8.16308mm)
  page written to test.svg
1 of 1 page converted in 0.157169 seconds
</pre>
