### ISSUE TITLE
EPS file from beamer package not found

### ISSUE THREAD

**Issue by ernstmoritzhahn** [mgieseki/dvisvgm#69]
When running dvisvgm on the dvi file produced from
```
\documentclass{beamer}
\mode<presentation>
\begin{document}
\begin{frame}
  \frametitle{Results}
  \footnotesize
  \begin{thebibliography}{10}
    
  \bibitem{Item1}
    Author 1 and Author 2.
    \newblock Title.
    \newblock In {\em Conference}, pages 1--15
  \end{thebibliography}
\end{frame}
\end{document}
```
I get the warning
`  WARNING: file 'beamericonarticle.eps' not found in special 'psfile'`
and the symbol from 'beamericonarticle.eps' is not included in the generated svg file. If I place 'beamericonarticle.eps' in the same directory as the dvi file, the warning disappears. However, the content of 'beamericonarticle.eps' is still not included in the generated svg file, which might however be a separate problem. I am using the latest version of dvisvgm from the git and am quite sure that postscript support is activated.

**Comment by mgieseki** [comment]
Yes, that's right. At the moment, dvisvgm looks up files included with `psfile` only in the current working directory. It shouldn't be too complicated to take eps files present in the texmf tree into account as well. I'll have a look.
The other issue concerning the missing bitmap image is more complicated. dvisvgm only supports a subset of PostScript operators. Especially, the bitmap operators, like `colorimage` as used in file beamericonarticle.eps, are currently ignored. That's why the document symbol is missing in the generated svg.
