### ISSUE TITLE
Add --with-kpathsea option (and similar) to configure script

### ISSUE THREAD

**Issue by ernstmoritzhahn** [mgieseki/dvisvgm#71]
It would be useful to have an option --with-kpathsea to specify the location of the kpathsea library. For instance, when using macports to install texlive, then kpathsea will be located in /opt/local where the configure script does not find it automatically. Without such an option, configuring dvisvgm is somewhat tricky (I used CLFAGS to specify temporarily library and inclusion directories). The same holds for the other libraries on which dvisvgm depends.

**Comment by mgieseki** [comment]
While this might be useful for some cases, adding these options for libraries without pkgconfig support (as kpathsea) is quite annoying and needs a lot of manual fiddling. Thus, at the moment, I don't rank it high on my priority list.
dvisvgm and its dependencies are available through MacPorts. So maybe there's already an environment that can be used to build it more easily. I'm not a Mac guy, so that's just a guess.
