### ISSUE TITLE
feature request: option to read from stdin

### ISSUE THREAD

**Issue by smasher164** [mgieseki/dvisvgm#86]
I'd like to be able to pipe in a dvi file that is generated on the fly, but currently I have to create a temporary file first. The environment in which I run dvisvgm makes it so that the only input I can send to a program is via stdin. Is it possible to add a flag, let's say `-i, --stdin` that reads a dvi file from stdin? An example would be
```
cat foo.dvi | dvisvgm --stdin
```
This would mirror the stdout flag that already exists.

**Comment by mgieseki** [comment]
dvisvgm can't process DVI data on the fly by serially reading from an input stream because it requires information from all pages in order to create correct hyperlinks for example. Therefore, it would be necessary to read the entire DVI document from the stream and to write it to a temporary file or to keep it in memory.
I have to look into this in more detail and put it on my feature list. However, I can't promise to implement it in the near future.

**Comment by smasher164** [comment]
Thanks for replying! I looked through the source of [dvi2bitmap](https://sourceforge.net/projects/dvi2bitmap/) and although they accept input from stdin, I don't think they handle links in the same way.
In that case, if dvisvgm can't process DVI data serially, then can it copy the contents of stdin into a temporary file? I already do this in a [wrapper script](https://github.com/smasher164/svglatex), and I wonder if this solution is worthy of incorporating into a feature.

**Comment by mgieseki** [comment]
I think, reading from stdin would be a nice addition. It's not complicated to copy the read data to a temporary DVI file. Extending dvisvgm's current I/O handling appropriately needs some work, though.
