### ISSUE TITLE
Please allow bypassing bundled libs (so that system package equivalents are used, instead)

### ISSUE THREAD

**Issue by hartwork** [mgieseki/dvisvgm#90]
Hi Martin,

dvisvgm bundles a number of libraries, some of which have standalone packages in modern Linux distributions. Inspecting the `libs` folder I find these bundled dependencies (— and their avalability in Gentoo for an example):

* `brotli` — `app-arch/brotli` 1.0.5
* `clipper` — n/a
* `ff-woff` — n/a
* `variant` — `dev-libs/boost` 1.65.0
* `woff2` — `media-libs/woff2` 1.0.2
* `xxHash` — `dev-libs/xxhash` 0.6.4

When a vulnerability (or some other bug) in one of these dependencies is fixed, the user only benefits with the next release of dvisvgm, provided you keep all of these up to date yourself for every release. It would be awesome, to have configure options to compile and link against system wide versions of these packages so that when they are updated all using apps — including dvisvgm — get the fix.
There is more on that topic at https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies but it's not specific to Gentoo; Debian tries to patch out bundled dependencies as well. If there were options to bypass the bundles, it would make user life more secure and downstream life less patching effort.

What do you think?

**Comment by mgieseki** [comment]
Hi Sebastian,

actually, unbundling some of the libraries is already on my to-do list since we also have a no-bundled-libraries policy for Fedora. The unbundling currently takes place in the spec file used to build the rpm. I've kept the libraries for now to simplify building _dvisvgm_ for TeX Live.

I'll discuss the topic with the TeX Live maintainers and will probably unbundle _brotli_, _woff2_ and _xxhash_. _ff-woff_ is a reduced version of _libfontforge_ where the latter can be used alternatively. On Windows the latter is hard to build. Therefore, I'm currently working on a complete replacement for _ff-woff_.

As I'd like to avoid adding a dependency on _boost_, I chose the C++17-compliant [_variant_ class by mpark](https://github.com/mpark/variant) which is a is a header-only implementation. So there's no binary code linked in this case.

**Comment by hartwork** [comment]
If there was a way to use system brotli, woff2 and xxhash, that would be awesome.

**Comment by mgieseki** [comment]
I added the new option `--enable-bundled-libs` to the `configure` script which must now be used to link the bundled libraries _brotli_, _woff2_, and _xxhash_, i.e. it retains the previous behavior. If it's omitted, `configure` looks for the corresponding system libraries.

**Comment by hartwork** [comment]
Pretty cool, even with bundles off by default, nice!

Two small things caught my attention:
* edd9067851f671254c9c03d083efc544b5fdcc9a adds a typo `'want` with a stray single tick to the readme [at line 120](https://github.com/mgieseki/dvisvgm/commit/edd9067851f671254c9c03d083efc544b5fdcc9a#diff-04c6e90faac2675aa89e2176d2eec7d8R120)
* https://dvisvgm.de/Downloads/ does not mention xxHash as a dependency yet

**Comment by mgieseki** [comment]
Good catches. I've fixed the readme/website issues locally and will push them shortly.
