### ISSUE TITLE
Bundle Kpathsea

### ISSUE THREAD

**Issue by spl** [mgieseki/dvisvgm#96]
I wonder if you would consider bundling Kpathsea as you bundle other libraries.

I want to create a dvisvgm formula for Homebrew, so that it's easy to install on macOS. Kpathsea appears to be the main showstopper (as has been previously [discovered](https://tobywf.com/2017/04/build-dvisvgm-kpathsea-on-macos/)). I made initial steps toward making Kpathsea easy to install with Homebrew by creating a repository of [Kpathsea release archives](https://github.com/spl/kpathsea-releases). But then I realized that dvisvgm already bundles other libraries, so why not Kpathsea? It seems like you already have most of the infrastructure to deal with Kpathsea existing as a system library (e.g. `--enable-bundled-libs` and `--disable-bundled-libs`).

Note that [spl/kpathsea-releases](https://github.com/spl/kpathsea-releases) might help you get a Kpathsea library that can be bundled.

I didn't see this mentioned after a brief search of the issues here. The most closely related seems to be #71.

**Comment by mgieseki** [comment]
Thanks for your suggestion. However, I don't think, it's a good idea to bundle Kpathsea. The library is tightly linked to the corresponding TeX Live version and its configuration. That's probably why it's only distributed as part of it. I already tried to build dvisvgm with different Kpathsea versions in the past, but the resulting binary didn't find any file in the TeX Live tree. So it's important to keep Kpathsea in sync with the TeX Live environment present on the system.

Actually, I'd like to drop most of the bundled 3rd party libraries. The main reasons for keeping them for now are: 
- dvisvgm uses slightly modified versions (_clipper_ and _fontforge_).
- The TeX Live maintainers asked to bundle them in order to simplify their build process. Since no other utility in TeX Live requires them, they prefer not to put them in the dedicated `libs` folder.

**Comment by spl** [comment]
Thanks for your feedback.

> I already tried to build dvisvgm with different Kpathsea versions in the past, but the resulting binary didn't find any file in the TeX Live tree. So it's important to keep Kpathsea in sync with the TeX Live environment present on the system.

Hmm, do I understand correctly that some Kpathsea binaries (e.g. `kpsewhich`, etc.) have hardcoded references to other files in the TeXLive build directories? In [spl/kpathsea-releases](https://github.com/spl/kpathsea-releases), I've tested that the releases build, but I haven't tested that the binaries work. In fact, I'm not sure what all I should do for that.

The versions of dvisvgm that come with TeXLive generally seem to be pretty old. It seems to be a difficult task to get standalone dvisvgm releases for macOS. Do you have any thoughts on that?

**Comment by spl** [comment]
> I already tried to build dvisvgm with different Kpathsea versions in the past, but the resulting binary didn't find any file in the TeX Live tree.

Oh, I think I misunderstood. You meant the resulting `dvisvgm` binary, right? That doesn't bode well for my attempt to install dvisvgm with a standalone Kpathsea installation. Do you think this [blog post](https://tobywf.com/2017/04/build-dvisvgm-kpathsea-on-macos/) and [gist](https://gist.github.com/tobywf/aeeeee63053aaaa841b4032963406684) about building dvisvgm on macOS would result in the same problem?

**Comment by mgieseki** [comment]
> Hmm, do I understand correctly that some Kpathsea binaries (e.g. kpsewhich, etc.) have hardcoded references to other files in the TeXLive build directories?

I must confess I'm not an expert for kpathsea.  There are a couple of hardcoded relative paths in libkpathsea that depend on several variables like `SELFAUTOLOC` and `SELFAUTOPARENT` which seem to get hardcoded during the build process but can also be overridden by environment variables of the same name. 

> The versions of dvisvgm that come with TeXLive generally seem to be pretty old. It seems to be a difficult task to get standalone dvisvgm releases for macOS. Do you have any thoughts on that?

That's indeed a problem. Since TeX Live only updates the binaries once a year and doesn't provide intermediate ones, some bug fix and/or feature releases are not available in a timely manner. I'm not a Mac user and don't have one available, so I can't really tell anything that's specific to that system. Maybe one of the TeX Live maintainers responsible for the Mac builds can give you more helpful information. They should be reachable through the TL mailing list.

>Oh, I think I misunderstood. You meant the resulting dvisvgm binary, right? 

Yes, exactly.

> That doesn't bode well for my attempt to install dvisvgm with a standalone Kpathsea installation. Do you think this blog post and gist about building dvisvgm on macOS would result in the same problem?

As far as I understood Toby in one of the closed dvisvgm tickets, he was able to successfully build dvisvgm on macOS using the method described in his blog post. 
BTW, dvisvgm is also available from MacPorts. Maybe that's an alternative to building it yourself.

**Comment by spl** [comment]
> BTW, dvisvgm is also available from MacPorts. Maybe that's an alternative to building it yourself.

Too late! 😏

[This](https://github.com/spl/homebrew-dvisvgm/blob/bc61d99903dec837b076c6ecd6c914c1fd2b99d9/Formula/dvisvgm.rb) is what I've got so far. Would you mind taking a quick peak and letting me know what you think?

I think I got most of the dependencies, though I didn't find anything about Ghostscript or zlib dependencies in the `./configure` output, and it built without me specifying those dependencies. Are there any `./configure` flags I should add/change? I suppose one thing would be to add an option for `--with-ttfautohint`.

Also, are there example `dvisvgm` commands that I could run to test the installation?

Thanks for your time!

**Comment by mgieseki** [comment]
Looks good to me so far. Regarding zlib, configure should report something like
```
checking for gzopen in -lz... yes
```
and it probably does because configure would fail otherwise as zlib is mandatory. If the Ghostscript development files can't be found when building dvisvgm, it's looked up during runtime. You can check if the output of `dvisvgm -V1` lists Ghostscript. In case it's missing, dvisvgm can't find the shared GS library on its own and you have to specify the path using option `--libgs` or environment variable `LIBGS`.

By default, dvisvgm uses the FontForge autohinter so that you don't need TTFAutohint. The latter usually produces better hinting results, though. This is only relevant in conjunction with dvisvgm option `--font-format`, e.g. `--font-format=woff,autohint`.

The dvisvgm sources come with a test suite that you could run (`make check`) to check the core functionality. If that's to much trouble in your case, I recommend at least to create a simple DVI file like  `tests/data/sample.dvi` present in the dvisvgm tarball, and let dvisvgm convert it (no special command-line options required). If there are no error messages, Kpathsea works correctly.

**Comment by spl** [comment]
Okay, I fixed the `texmf.cnf` warning by saving the file in one of the directories searched. But I haven't fixed the others.

```
WARNING: map file ps2pk.map not found
WARNING: map file pdftex.map not found
WARNING: map file dvipdfm.map not found
WARNING: map file psfonts.map not found
WARNING: none of the default map files could be found
```

**Comment by mgieseki** [comment]
> Great! Thanks so much for the feedback.

You're welcome.

> Should I then be concerned about those warnings?

Probably yes because dvisvgm can't find any of the required map files which may lead to wrong characters in the generated file.  Does `kpsewhich` find them? Maybe there's just a package missing, e.g. dvips.

Nonetheless it's positive that you don't get warnings about missing TFM or PFB files. Did you convert the DVI file inside the folder `tests/data`? If so, please copy `sample.dvi` to a different folder and convert it again. The `data` folder contains all additional files required to process `sample.dvi` properly. However, this shouldn't be necessary as dvisvgm is supposed to find them in the TeX directory tree too.

You can also check the conversion results visually. The easiest way to do that is to call dvisvgm with option `--no-fonts` and to open the generated SVG file in a web browser, for example.

**Comment by mgieseki** [comment]
If you don't mind, I close this ticket for now. Feel free to reopen it if necessary.

**Comment by spl** [comment]
Absolutely! Sorry, I've been meaning to get back to you. I realized I needed to do more homework on the TeXLive and macOS installation. But none of it is related to the topic of this ticket (bundling Kpathsea), which I also agree that you don't want to do.
