### ISSUE TITLE
Feature request: reduce the output size with compression

### ISSUE THREAD

**Issue by sadqiang** [mgieseki/dvisvgm#97]
I found a good tool to compress SVG [here](https://vecta.io/nano#).
It will be better if dvisvgm can also reduce the output with compression.

**Comment by sadqiang** [comment]
Compression I said above means trimming the negligible contents in the file.
For example, by removing any points with almost similar slope or gradient, a curve that is  made of 1000 too-dense points can be simplified to a curve that is just made of 20 points.

**Comment by mgieseki** [comment]
Optimizing the entire SVG output is beyond the scope of the project at the moment. As you wrote, there are several separate tools that can be used to post-process the generated files. To me it's currently more important to get correct conversion results rather than small files.
Concerning a reduced number of decimal places, you can use option `--precision`. I put the reduction of path points on my to-do list but probably can't work on it anytime soon.

**Comment by sadqiang** [comment]
I understood your situation. Thank you for considering this feature request. 👍

**Comment by mgieseki** [comment]
I agree that it would be nice but it's something that, in most cases, can't be done instantly when creating the path elements but requires post-processing of a certain sub-tree or the whole SVG document. Also, deciding when and what to group without bloating the document even further isn't an easy task if it's supposed to work for arbitrary SVG files. Thus, a useful post-processor requires some clever algorithms to determine proper optimizations for each file. Since I don't have the time to implement this myself, I currently don't plan to add a general "SVG optimizer" to dvisvgm. Sorry.

**Comment by mgieseki** [comment]
I've added a couple of optimizations to the recent version 2.7.
