### ISSUE TITLE
Errors building with system native Ghostscript shared library

### ISSUE THREAD

**Issue by svenper** [mgieseki/dvisvgm#98]
The bundled Ghostscript library works, but there are errors building the Ghostscript related functions using the system shared library, as seen in the last screenfuls of the [full texlive build log](https://gist.githubusercontent.com/svenper/9094adcf179d996ab5283f28b598f95f/raw).

-----

texlive 2018 [`1409b83`](https://github.com/TeX-Live/texlive-source/commit/1409b8392fd32674db2605eb0cd2e85fc59e6d28)
dvisvgm 2.6.1
ghostscript 9.26
linux 4.14.87
musl libc 1.1.20

**Comment by mgieseki** [comment]
This seems to be an issue with the TeX Live build system because `configure` prints the following warning:
`configure: not linking to libgs, trying to arrange for dynamic loading`
It's not part of dvisvgm's original configuration script. I can't really help here since I don't know much about the TL build system. The people on the TL mailing list are probably more knowledgeable in this case.
